# Generated by Django 2.2 on 2019-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='dias_trabajados',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
