# Generated by Django 2.2 on 2019-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nomina_dias_trabajados'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clave',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
