# Generated by Django 2.2 on 2019-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_producto_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='empleado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
