# Generated by Django 2.2 on 2019-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_empleado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
