# Generated by Django 2.2 on 2019-05-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_empleado_nss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='pago_mes',
            new_name='pago_dia',
        ),
    ]
