# Generated by Django 2.2 on 2019-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190505_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='dias_trabajados',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='horas_trabajadas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='monto_pago',
            field=models.FloatField(default=0),
        ),
    ]
