# Generated by Django 2.2 on 2019-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190505_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='tipo',
            field=models.CharField(choices=[('salario', 'Asalariado'), ('horas', 'Por Hora')], default='horas', max_length=255),
            preserve_default=False,
        ),
    ]
